name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ninja
      run: |
        choco install ninja -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
        dir C:\ProgramData\chocolatey\bin

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        cd ..
        echo "$(pwd)/vcpkg" >> $GITHUB_PATH 
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        vcpkg install --triplet x64-windows-static

    - name: Configure CMake
      run: |
        ninja --version
        mkdir build
        cd build
        cmake .. --preset vcpkg

    - name: Build
      run: |
        cd build
        cmake --build . --config Release
